spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skill_management
    username: postgres
    password: Telnet*1234


  r2dbc:
    url: r2dbc:postgresql://localhost:5432/skill_management
    username: postgres
    password: Telnet*1234

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/skill_management
    user: postgres
    password: Telnet*1234
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver

logging:
  level:
    liquibase: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
